### ISSUE TITLE
[PE-D] Delete feature is hard to use

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F09-1/tp#208]
The delete command requires users to type the case sensitive full name of the person to delete, which can make it hard to delete contacts quickly and efficiently

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Jiaaa-yang/ped#3

**Comment by DALIN-Prog** [comment]
Considering that deleting is simply wiping off the data from the storage and undo command is not implemented, it make sense to have a delete functionality that requires user to have exact match to player's name. This is important so that user knows that he/she is deleting the particular player. Moreover, as opposed to using indexing, as a human being generally we remember a person by their name and a true fast typist will not type name in alternate casing.
